name: ml_ops
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - coverage==7.6.9
      - hydra-core~=1.3.2
      - invoke==2.2.0
      - matplotlib~=3.9.2
      - mkdocs==1.5.3
      - mkdocs-material==9.4.6
      - mkdocstrings-python==1.12.2
      - numpy~=2.2.1
      - omegaconf~=2.3.0
      - pandas~=2.2.3
      - pre-commit==3.5.0
      - python-dotenv==1.0.1
      - pytest==8.3.4
      - ruff==0.1.3
      - scikit-learn==1.6.0
      - scipy==1.15.0
      - seaborn==0.13.2
      - torch==2.5.1
      - torch-geometric==2.6.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - typer==0.15.1
      - wandb==0.19.2
