wandb:
  project_name: "gnn-siouxfalls"
  sweep: True
 
data:
  data_class: SiouxFalls24Zones
  dataset_name: sioux_falls_simulation_24_zones_OD_10K
  edge_feature_to_weight_index: 1
  edge_feature_identity_matrix: True

scaling: StandardScaler

model:
  layer_type:
    - GCN
    - GAT
  hidden_dim: 
    - 32
    - 64
  num_gnn_layers:
    - 1
    - 2
    - 3

train:
  lr:
    - 0.01
    - 0.1
    - 0.2
  batch_size:
    - 32
    - 64
  epochs: 
    - 10
    - 50
    - 100
  weight_decay: 0.0001
  loss_fn: MSELoss ## L1Loss
  optimizer: AdamW ## AdamW
  device: cpu
  random_seed: 42

inference:
  run: False
  model_path: "" #<run_dir>/models/model.pth