model:
  layer_type: GCN
  hidden_dim: 64
  num_gnn_layers: 2

train:
  lr: 0.1
  batch_size: 32
  epochs: 150
  weight_decay: 1e-5
  device: cpu
  optimizer: AdamW ## AdamW
  loss_fn: L1Loss ## L1Loss
  random_seed: 42

data:
  data_class: SiouxFalls24Zones
  dataset_name: sioux_falls_simulation_24_zones_OD_2K
  edge_feature_to_weight_index: 1
  edge_feature_identity_matrix: True
  diffusion: False

scaling:

inference:
  run: False
  model_path: "" #<run_dir>/models/model.pth

wandb:
  project_name: "gnn-siouxfalls"
