model:
  layer_type: DiffusionTestModel
  hidden_dim: 64
  num_gnn_layers: 3

train:
  lr: 0.03
  batch_size: 1
  epochs: 1000
  weight_decay: 1e-4
  device: mps
  optimizer: AdamW ## AdamW
  loss_fn: MSELoss ## L1Loss
  random_seed: 42

data:
  data_class: SiouxFalls24Zones
  dataset_name: sioux_falls_simulation_24_zones_OD_10K
  edge_feature_to_weight_index: 1
  edge_feature_identity_matrix: True

scaling: StandardScaler

inference:
  run: False
  model_path: "" #<run_dir>/models/model.pth

wandb:
  project_name: "gnn-siouxfalls"
