model:
  layer_type: DiffusionTestModel
  hidden_dim: [16,32,64]
  num_gnn_layers: [1,2,3,4,5,6]

train:
  lr: [0.01,0.03,0.05,0.07,0.09]
  batch_size: [1,16,32,64,128]
  epochs: 200
  weight_decay: [0.001,0.0001,0.00001]
  loss_fn: MSELoss ## L1Loss
  optimizer: AdamW ## AdamW
  device: cpu
  random_seed: 42

data:
  data_class: SiouxFalls24Zones
  dataset_name: sioux_falls_simulation_24_zones_OD_10K
  edge_feature_to_weight_index: 1
  edge_feature_identity_matrix: True

scaling: StandardScaler

inference:
  run: False
  model_path: "" #<run_dir>/models/model.pth

wandb:
  project_name: "gnn-siouxfalls"
