model:
  type: GCN
  hidden_dim: 64
  num_gnn_layers: 6
  
train:
  lr: 0.03
  batch_size: 32
  epochs: 1000
  weight_decay: 1e-5
  device: cpu
  optimizer: AdamW ## AdamW
  loss_fn: L1Loss ## L1Loss
  random_seed: 42

data:
  data_class: SiouxFalls24Zones
  dataset_name: sioux_falls_simulation_24_zones_OD_2K
  processed_dir: data/processed
  raw_dir: data/raw

scaling: StandardScaler

output:
  model_dir: models/
  figures_dir: reports/figures/

inference:
  run: False
  model_path: "" #<run_dir>/models/model.pth

hydra:
  run:
    dir: results/${now:%Y%m%d_%H%M%S}_${data.dataset_name}

wandb:
  project_name: ${data.dataset_name}