lr:
  - 0.01
  - 0.1
  - 0.2
batch_size:
  - 32
  - 64
epochs: 
  - 100
  - 200
  - 300
weight_decay: 
  - 0.0001
  - 0.001
loss_fn: 
  - MSELoss
  - L1Loss
optimizer: AdamW
device: cpu
random_seed: 42
